source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Tropicalytics_Example' do
  pod "Tropicalytics", :path => "../"
end

target 'Tropicalytics_Tests' do
  pod "Tropicalytics", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
